import Head from 'next/head';

const HomePage = () => {

  const consola = () => {
    console.log('hello world');
  }
  
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Culii</h1>
        <button onClick={consola}>press me</button>
      </main>
    </div>
  )
}

export default HomePage;
