import Head from 'next/head';

const PlanBasicoPage = () => {

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Plan Basico</h1>
        <h2>U$S 98</h2>
      </main>
    </div>
  )
}

export default PlanBasicoPage;
